
[arcane_gold]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[brass]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[bronze]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[cast_iron]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[coal_coke]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[constantan]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[electrum]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[ender_pearl]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[enderium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[flour]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[graphite]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[invar]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[lumium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[obsidian]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[red_alloy]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[salt]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[signalum]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[silicon]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[steel]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[wood]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false
