
[amethyst]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[baronyte]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[blazium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[bloodstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[blue_gemstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[charged_runium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[crystallite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[elecanium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[emberstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[gemenyte]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[ghastly]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[ghoulish]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[green_gemstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[jade]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[jewelyte]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[limonite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[lunar]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[lyon]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[mystite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[ornamyte]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[purple_gemstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[red_gemstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[rosite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[runium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[rusted_iron]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[shyregem]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[shyrestone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[skeletal]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[varsium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[white_gemstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[yellow_gemstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
