
[baronyte]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[blazium]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[elecanium]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[emberstone]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[ghastly]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[ghoulish]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[limonite]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[lunar]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[mystite]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[rosite]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[rusted_iron]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[shyrestone]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[skeletal]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[varsium]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
