
[aeternium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[amber]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[terminite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[thallasium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
