
[drenched_iron]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[fireite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[inert_crystal]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[swift_alloy]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
