
[aethium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[erodium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[ionite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[kyronite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[litherite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[lonsdaleite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[nanorite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[pladium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[xerothium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
