
[bitumen]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[fluorite]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[potassium_nitrate]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[ruby]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[sapphire]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[sulfur]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false
