
[lithium]
    active = true
    overwrite_texture = true
    add_tooltip = true

[refined_glowstone]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[refined_obsidian]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
