
[charcoal]
    overwrite_texture = true
    add_tooltip = true

[lithium]
    overwrite_texture = true
    add_tooltip = true

[refined_glowstone]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[refined_obsidian]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
