
[aluminum]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[bismuth]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[boron]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[cobalt]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[iridium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[lead]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[lithium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[magnesium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[nickel]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[osmium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[platinum]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[silver]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[thorium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[tin]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[titanium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[tungsten]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[uranium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false

[zinc]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    replace_output = false
    replace_input = false
