
[aluminum]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[bismuth]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[cobalt]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[iridium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[lead]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[nickel]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[osmium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[platinum]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[silver]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[tin]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[titanium]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[tungsten]
    active = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[uranium]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[zinc]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false
