
[blazing_crystal]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[energized_steel]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[niotic_crystal]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[nitro_crystal]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[overcharged]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[spirited_crystal]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[uraninite]
    active = true
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
