
[hepatizon]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[manyullyn]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[pig_iron]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[queens_slime]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[slimesteel]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true

[tinkers_bronze]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
