
[iron]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[gold]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[netherite]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[copper]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[lapis]
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[diamond]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[emerald]
    overwrite_texture = true
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[redstone]
    add_tooltip = true
    add_element = true
    add_tag = true

[quartz]
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false

[coal]
    add_tooltip = true
    add_element = true
    add_tag = true
    hide_jei = false
    remove_recipe = false
    replace_output = false
