
[[ore]]
    id = "amethyst"
    dim = ["overworld"]
    displayName = "Amethyst Ore"
    active = true

    [ore.texture]
        name = "aoa3/amethyst"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [13, 31]
            size = 7
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

[[ore]]
    id = "baronyte"
    dim = ["barathos"]
    displayName = "Baronyte Ore"
    active = true

    [ore.texture]
        name = "aoa3/baronyte"

    [[ore.extra_rules]]
        strata = "baron_stone"
        active_only = true

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [24, 36]
            size = 8
            count = 3

            [ore.values.gen.dimensions]
                names = ["aoa3:barathos"]

[[ore]]
    id = "blazium"
    dim = ["barathos"]
    displayName = "Blazium Ore"
    active = true

    [ore.texture]
        name = "aoa3/blazium"

    [[ore.extra_rules]]
        strata = "hellstone"
        active_only = true

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [0, 20]
            size = 8
            count = 2

            [ore.values.gen.dimensions]
                names = ["aoa3:barathos"]


[[ore]]
    id = "bloodstone"
    dim = ["abyss"]
    displayName = "Bloodstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/bloodstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 64]
            size = 12
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:abyss"]

[[ore]]
    id = "blue_gemstone"
    dim = ["crystevia"]
    displayName = "Blue Gemstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/blue_gemstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 115]
            size = 13
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:crystevia"]

[[ore]]
    id = "charged_runium"
    dim = ["deeplands"]
    displayName = "Charged Runium Ore"
    active = true

    [ore.texture]
        name = "aoa3/charged_runium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"
        [[ore.values.gen]]
            type = "CLUSTER"
            height = [70, 115]
            size = 18
            count = 5

            [ore.values.gen.dimensions]
                names = ["aoa3:deeplands"]

[[ore]]
    id = "crystallite"
    dim = ["haven"]
    displayName = "Crystallite Ore"
    active = true

    [ore.texture]
        name = "aoa3/crystallite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 70]
            size = 12
            count = 8

            [ore.values.gen.dimensions]
                names = ["aoa3:haven"]

[[ore]]
    id = "elecanium"
    dim = ["runandor"]
    displayName = "Elecanium Ore"
    active = true

    [ore.texture]
        name = "aoa3/elecanium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 35]
            size = 5
            count = 3

            [ore.values.gen.dimensions]
                names = ["aoa3:runandor"]

[[ore]]
    id = "emberstone"
    dim = ["nether"]
    displayName = "Emberstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/emberstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [3, 32]
            size = 5
            count = [2, 3, 4]

            [ore.values.gen.biomes]
                types = ["Nether"]

[[ore]]
    id = "gemenyte"
    dim = ["creeponia_pressed"]
    displayName = "Gemenyte Ore"
    active = true

    [ore.texture]
        name = "aoa3/gemenyte"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [21, 37]
            size = 6
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:creeponia"]

[[ore]]
    id = "ghastly"
    dim = ["greckon"]
    displayName = "Ghastly Ore"
    active = true

    [ore.texture]
        name = "aoa3/ghastly"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 60]
            size = 7
            count = 2

            [ore.values.gen.dimensions]
                names = ["aoa3:greckon"]

[[ore]]
    id = "ghoulish"
    dim = ["greckon"]
    displayName = "Ghoulish Ore"
    active = true

    [ore.texture]
        name = "aoa3/ghoulish"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 30]
            size = 7
            count = 2

            [ore.values.gen.dimensions]
                names = ["aoa3:greckon"]


[[ore]]
    id = "green_gemstone"
    dim = ["crystevia"]
    displayName = "Green Gemstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/green_gemstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 115]
            size = 13
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:crystevia"]

[[ore]]
    id = "jade"
    dim = ["overworld"]
    displayName = "Jade Ore"
    active = true

    [ore.texture]
        name = "aoa3/jade"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 40]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 40]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                types = ["OCEANS", "RIVER"]
                names = ["minecraft:beach"]

[[ore]]
    id = "jewelyte"
    dim = ["creeponia_pressed"]
    displayName = "Jewelyte Ore"
    active = true

    [ore.texture]
        name = "aoa3/jewelyte"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [21, 37]
            size = 6
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:creeponia"]

[[ore]]
    id = "limonite"
    dim = ["overworld"]
    displayName = "Limonite Ore"
    active = true

    [ore.texture]
        name = "aoa3/limonite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 1
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [25, 250]
            size = 7
            count = 15

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

[[ore]]
    id = "lyon"
    dim = ["iromine"]
    displayName = "Lyon Ore"
    active = true

    [ore.texture]
        name = "aoa3/lyon"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 64]
            size = 7
            count = 2

            [ore.values.gen.dimensions]
                names = ["aoa3:iromine"]

[[ore]]
    id = "mystite"
    dim = ["mysterium"]
    displayName = "Mystite Ore"
    active = true

    [ore.texture]
        name = "aoa3/mystite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 100]
            size = 9
            count = 2

            [ore.values.gen.dimensions]
                names = ["aoa3:mysterium"]

[[ore]]
    id = "ornamyte"
    dim = ["creeponia_primed"]
    displayName = "Ornamyte Ore"
    active = true

    [ore.texture]
        name = "aoa3/ornamyte"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [2, 15]
            size = 6
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:creeponia"]

[[ore]]
    id = "purple_gemstone"
    dim = ["crystevia"]
    displayName = "Purple Gemstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/purple_gemstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 115]
            size = 13
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:crystevia"]

[[ore]]
    id = "red_gemstone"
    dim = ["crystevia"]
    displayName = "Red Gemstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/red_gemstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 115]
            size = 13
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:crystevia"]

[[ore]]
    id = "rosite"
    dim = ["overworld"]
    displayName = "Rosite Ore"
    active = true

    [ore.texture]
        name = "aoa3/rosite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 50]
            size = 10
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

[[ore]]
    id = "runium"
    dim = ["overworld"]
    displayName = "Runium Ore"
    active = true

    [ore.texture]
        name = "aoa3/runium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [5, 40]
            size = 5
            count = 2

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

[[ore]]
    id = "shyrestone"
    dim = ["shyrelands"]
    displayName = "Shyrestone Ore"
    active = true

    [ore.texture]
        name = "aoa3/shyrestone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [65, 105]
            size = 5
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:shyrelands"]

[[ore]]
    id = "shyregem"
    dim = ["shyrelands"]
    displayName = "Shyregem Ore"
    active = true

    [ore.texture]
        name = "aoa3/shyregem"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [65, 105]
            size = 5
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:shyrelands"]


[[ore]]
    id = "skeletal"
    dim = ["precasia"]
    displayName = "Skeletal Ore"
    active = true

    [ore.texture]
        name = "aoa3/skeletal"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [0, 40]
            size = 6
            count = 2

            [ore.values.gen.dimensions]
                names = ["aoa3:precasia"]

[[ore]]
    id = "varsium"
    dim = ["barathos"]
    displayName = "Varsium Ore"
    active = true

    [ore.texture]
        name = "aoa3/varsium"

    [[ore.extra_rules]]
        strata = "baron_stone"
        active_only = true

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [24, 64]
            size = 8
            count = 2

            [ore.values.gen.dimensions]
                names = ["aoa3:barathos"]

[[ore]]
    id = "white_gemstone"
    dim = ["crystevia"]
    displayName = "White Gemstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/white_gemstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 115]
            size = 13
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:crystevia"]

[[ore]]
    id = "yellow_gemstone"
    dim = ["crystevia"]
    displayName = "Yellow Gemstone Ore"
    active = true

    [ore.texture]
        name = "aoa3/yellow_gemstone"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 5
            explosionResistance = 10

        [ore.values.forge]
            harvestLevel = 4
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 115]
            size = 13
            count = 4

            [ore.values.gen.dimensions]
                names = ["aoa3:crystevia"]