[[ore]]
    id = "source_gem"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Source Gem Ore"
    active = true

    [ore.texture]
        name = "ars_nouveau/source_gem"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 0
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 32]
            size = 8
            count = 5

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 60]
            size = 8
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 50]
            size = 8
            count = 4

            [ore.values.gen.biomes]
                types = ["THE_END"]