[[ore]]
    id = "aquamarine"
    dim = ["overworld_sand"]
    displayName = "Aquamarine Ore"
    active = true

    [ore.texture]
        name = "astralsorcery/aquamarine"

    [[ore.extra_rules]]
        strata = "sand"
        active_only = true

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "SAND"
            destroyTime = 0.5
            explosionResistance = 0.5

        [ore.values.forge]
            harvestLevel = -1
            harvestTool = "shovel"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 62]
            size = 4
            count = 5

            [ore.values.gen.biomes]
                types = ["OCEAN", "RIVER"]
                names = ["minecraft:beach"]

[[ore]]
    id = "rock_crystal"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Rock Crystal Ore"
    active = true

    [ore.texture]
        name = "astralsorcery/rock_crystal"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 0
            harvestTool = "pickaxe"


        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 45]
            size = 4
            count = 8

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

[[ore]]
    id = "starmetal"
    dim = ["overworld", "nether", "end", "atum", "moon", "mars", "mercury"]
    displayName = "Starmetal Ore"
    active = true

    [ore.texture]
        name = "astralsorcery/starmetal"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 1
            harvestTool = "pickaxe"
