[[ore]]
    id = "nebu"
    dim = ["atum"]
    displayName = "Nebu Ore"
    active = true

    [ore.texture]
        name = "atum/nebu"


    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 1
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 64]
            size = 8
            count = 1

            [ore.values.gen.dimensions]
                names = ["atum:atum"]