[[ore]]
    id = "ametrine"
    dim = ["end"]
    displayName = "Ametrine Ore"
    active = true

    [ore.texture]
        name = "byg/ametrine"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [10, 100]
            size = 4
            count = 10

            [ore.values.gen.biomes]
                names = ["byg:shattered_viscal_isles"]

[[ore]]
    id = "anthracite"
    dim = ["nether"]
    displayName = "Anthracite Ore"
    active = true

    [ore.texture]
        name = "byg/anthracite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 10
            count = 18

            [ore.values.gen.biomes]
                names = ["byg:brimstone_caverns"]

[[ore]]
    id = "emeraldite"
    dim = ["nether"]
    displayName = "Emeraldite Ore"
    active = true

    [ore.texture]
        name = "byg/emeraldite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 3
            count = 30

            [ore.values.gen.biomes]
                names = ["byg:wailing_garth"]


[[ore]]
    id = "lignite"
    dim = ["end"]
    displayName = "Lignite Ore"
    active = true

    [ore.texture]
        name = "byg/lignite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [10, 100]
            size = 12
            count = 15

            [ore.values.gen.biomes]
                names = ["byg:ethereal_clearing", "byg:ethereal_islands", "byg:ethereal_forest", "byg:viscal_isles", "byg:shattered_viscal_isles"]

[[ore]]
    id = "pendorite"
    dim = ["nether"]
    displayName = "Pendorite Ore"
    active = true

    [ore.texture]
        name = "byg/pendorite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 4
            count = 30

            [ore.values.gen.biomes]
                names = ["byg:forest_fault"]
