[[ore]]
    id = "apalachia"
    dim = ["twilight_dims"]
    displayName = "Apalachia Ore"
    active = true

    [ore.texture]
        name = "divinerpg/apalachia"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "NETHERRACK"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 7
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 10
            count = 9

            [ore.values.gen.dimensions]
                types = ["divinerpg:apalachia"]

[[ore]]
    id = "arlemite"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Arlemite Ore"
    active = true

    [ore.texture]
        name = "divinerpg/arlemite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 16] 
            size = 4
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 45]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 35]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "bloodgem"
    dim = ["nether"]
    displayName = "Bloodgem Ore"
    active = true

    [ore.texture]
        name = "divinerpg/bloodgem"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "NETHERRACK"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 6
            count = 8

            [ore.values.gen.biomes]
                types = ["NETHER"]

[[ore]]
    id = "eden"
    dim = ["twilight_dims"]
    displayName = "Eden Ore"
    active = true

    [ore.texture]
        name = "divinerpg/eden"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "NETHERRACK"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 10
            count = 9

            [ore.values.gen.dimensions]
                types = ["divinerpg:eden"]

[[ore]]
    id = "mortum"
    dim = ["twilight_dims"]
    displayName = "Mortum Ore"
    active = true

    [ore.texture]
        name = "divinerpg/mortum"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "NETHERRACK"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 9
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 10
            count = 9

            [ore.values.gen.dimensions]
                types = ["divinerpg:mortum"]

[[ore]]
    id = "realmite"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Realmite Ore"
    active = true

    [ore.texture]
        name = "divinerpg/realmite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 50] 
            size = 5
            count = 8

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 80]
            size = 5
            count = 7

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 70]
            size = 5
            count = 7

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "rupee"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Rupee Ore"
    active = true

    [ore.texture]
        name = "divinerpg/rupee"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 16] 
            size = 4
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 45]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 35]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "skythern"
    dim = ["twilight_dims"]
    displayName = "Skythern Ore"
    active = true

    [ore.texture]
        name = "divinerpg/skythern"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "NETHERRACK"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 8
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 10
            count = 9

            [ore.values.gen.dimensions]
                types = ["divinerpg:skythern"]

[[ore]]
    id = "torridite"
    dim = ["nether"]
    displayName = "Torridite Ore"
    active = true

    [ore.texture]
        name = "divinerpg/torridite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "NETHERRACK"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 6
            count = 8

            [ore.values.gen.biomes]
                types = ["NETHER"]

[[ore]]
    id = "wildwood"
    dim = ["twilight_dims"]
    displayName = "Wildwood Ore"
    active = true

    [ore.texture]
        name = "divinerpg/wildwood"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "NETHERRACK"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 6
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 10
            count = 9

            [ore.values.gen.dimensions]
                types = ["divinerpg:wildwood"]
