[[ore]]
    id = "draconium"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Draconium Ore"
    active = true

    [ore.texture]
        name = "draconicevolution/draconium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 16]
            size = 8
            count = 3

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 35]
            size = 8
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 70]
            size = 10
            count = 6

            [ore.values.gen.biomes]
                types = ["THE_END"]