[[ore]]
    id = "inert_crystal"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Inert Crystal Ore"
    active = true

    [ore.texture]
        name = "elementalcraft/inert_crystal"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 64]
            size = 8
            count = 6

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 90]
            size = 8
            count = 5

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 80]
            size = 8
            count = 5

            [ore.values.gen.biomes]
                types = ["THE_END"]