[[ore]]
    id = "bitumen"
    dim = ["overworld_sand"]
    displayName = "Bitumen Ore"
    active = true

    [ore.texture]
        name = "gem/bitumen"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "SAND"
            destroyTime = 0.5
            explosionResistance = 0.5

        [ore.values.forge]
            harvestLevel = -1
            harvestTool = "shovel"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [40, 160]
            size = 20
            count = 2

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

[[ore]]
    id = "fluorite"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Fluorite Ore"
    active = true

    [ore.texture]
        name = "gem/fluorite"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 1
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 30]
            size = 8
            count = 6

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [60, 90]
            size = 8
            count = 5

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [50, 80]
            size = 8
            count = 5

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "potassium_nitrate"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Potassium Nitrate Ore"
    active = true

    [ore.texture]
        name = "gem/potassium_nitrate"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 1
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 35]
            size = 5
            count = 5

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [45, 65]
            size = 5
            count = 5

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [35, 55]
            size = 5
            count = 5

            [ore.values.gen.biomes]
                types = ["THE_END"]


[[ore]]
    id = "ruby"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Ruby Ore"
    active = true

    [ore.texture]
        name = "gem/ruby"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 25]
            size = 5
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [45, 50]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [35, 40]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "sapphire"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Sapphire Ore"
    active = true

    [ore.texture]
        name = "gem/sapphire"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 3
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 25]
            size = 5
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [45, 50]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [35, 40]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "sulfur"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Sulfur Ore"
    active = true

    [ore.texture]
        name = "gem/sulfur"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 1
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 16]
            size = 7
            count = 3

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 50]
            size = 6
            count = 3

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 40]
            size = 6
            count = 3

            [ore.values.gen.biomes]
                types = ["THE_END"]
