[[ore]]
    id = "inferium"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Inferium Ore"
    active = true

    [ore.texture]
        name = "mysticalagriculture/inferium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 0
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 8
            count = 16

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 90]
            size = 8
            count = 8

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 80]
            size = 8
            count = 8

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "prosperity"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Prosperity Ore"
    active = true

    [ore.texture]
        name = "mysticalagriculture/prosperity"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 0
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 50]
            size = 8
            count = 12

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 60]
            size = 8
            count = 8

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 50]
            size = 8
            count = 8

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "soulium"
    dim = ["nether_soulstone"]
    displayName = "Soulium Ore"
    active = true

    [ore.texture]
        name = "mysticalagriculture/soulium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 0
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 128]
            size = 10
            count = 64

            [ore.values.gen.biomes]
                types = ["NETHER"]