[[ore]]
    id = "boron"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Boron Ore"
    active = true

    [ore.texture]
        name = "nuclearcraft/boron"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 30]
            size = 5
            count = 6

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [25, 50]
            size = 5    
            count = 5

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 40]
            size = 5
            count = 5

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "lithium"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Lithium Ore"
    active = true

    [ore.texture]
        name = "nuclearcraft/lithium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 30]
            size = 5
            count = 6

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [25, 50]
            size = 5
            count = 5

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 40]
            size = 5
            count = 5

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "magnesium"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Magnesium Ore"
    active = true

    [ore.texture]
        name = "nuclearcraft/magnesium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 25]
            size = 5
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [25, 45]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 35]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "thorium"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Thorium Ore"
    active = true

    [ore.texture]
        name = "nuclearcraft/thorium"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 30]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [25, 50]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 40]
            size = 4
            count = 3

            [ore.values.gen.biomes]
                types = ["THE_END"]
