[[ore]]
    id = "electrotine"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Electrotine Ore"
    active = true

    [ore.texture]
        name = "projectred-core/electrotine"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 64]
            size = 8
            count = 6

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 70]
            size = 8
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 60]
            size = 8
            count = 4

            [ore.values.gen.biomes]
                types = ["THE_END"]

[[ore]]
    id = "peridot"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Peridot Ore"
    active = true

    [ore.texture]
        name = "projectred-core/peridot"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 2
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [20, 25]
            size = 5
            count = 4

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [45, 50]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [35, 40]
            size = 4
            count = 4

            [ore.values.gen.biomes]
                types = ["THE_END"]