[[ore]]
    id = "dimensional_shard"
    dim = ["overworld", "nether", "end", "atum"]
    displayName = "Dimensional Shard Ore"
    active = true

    [ore.texture]
        name = "rftoolsbase/dimensional_shard"

    [ore.values]
        [ore.values.block]
            material = {color = "NONE"}
            soundType = "STONE"
            destroyTime = 3
            explosionResistance = 3

        [ore.values.forge]
            harvestLevel = 0
            harvestTool = "pickaxe"

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [1, 20]
            size = 2
            count = 2

            [ore.values.gen.biomes]
                blacklist = true
                types = ["NETHER", "THE_END"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [30, 50]
            size = 6
            count = 4

            [ore.values.gen.biomes]
                types = ["NETHER"]

        [[ore.values.gen]]
            type = "CLUSTER"
            height = [15, 40]
            size = 8
            count = 6

            [ore.values.gen.biomes]
                types = ["THE_END"]