#KubeJS Common Properties
#Sun Mar 09 16:30:18 CET 2025
serverOnly=false
packmode=default
ignoreCustomUniqueRecipeIds=false
saveDevPropertiesInConfig=false
hideServerScriptErrors=false
startupErrorReportUrl=
startupErrorGUI=false
matchJsonRecipes=true
debugInfo=false
announceReload=true
invertClassLoader=true
allowAsyncStreams=true
