name: Mod Suggestion
description: |
  Make a mod suggestion. List mods that you think should be supported by the programm. 
  Before reporting, make sure an issue hasn't been reported already.
labels: ["mod suggestion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this mod suggestion!
        If you would rather wish to fill out this issue in a full page and not this small window clich [here](https://github.com/MundM2007/Ultimate-Unification/issues/new?template=4-mod_suggestion.yaml)
  - type: textarea
    id: list
    attributes:
      label: List of Mods/Materials
      description: List of mods or materials that you wish were supported in this project. They should be somewhat known and have a decent number of downloads. I remain the right to decline any recommendations.
      placeholder: List the mods/materials
    validations:
      required: true