name: Question
description: |
  Pose a question to a specific thing about the code or programm.
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: A clear and concise description of the Question
      placeholder: "Example: What does [...] do"
    validations:
      required: true