name: Question
description: |
  Pose a question to a specific thing about the code or programm.
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        If you would rather wish to fill out this issue in a full page and not this small window clich [here](https://github.com/MundM2007/Ultimate-Unification/issues/new?template=5-question.yaml)
  - type: textarea
    id: question
    attributes:
      label: Question
      description: A clear and concise description of the Question
      placeholder: "Example: What does [...] do"
    validations:
      required: true
