name: Game Issue
description: |
  Report a game issue. A game issue accures when some error is shown in chat after joining a world or the game refuses to launch. 
  Before reporting, please use the search function to make sure an issue hasn't been reported already. This avoids duplicates.
labels: ["game issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this game issue report!
  - type: textarea
    id: describe-issue
    attributes:
      label: Describe the issue
      description: A clear and concise description of what the issue is. If applicable add screenshots to help explain the problem.
      placeholder: Whats happening?
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: If it only occurs when doing something add the steps here.
      placeholder: When is it happening?
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of Minecraft are you using?
      options:
        - 1.16.5
      default: 0
    validations:
      required: true
  - type: textarea
    id: related-files
    attributes:
      label: Related Files
      description: Please upload realted files, these Include the minecraft latest.log file, but it can also be required that python code config files are needed or a modlist.
      placeholder: paste files or link to them here
    validations:
      required: true