[mods]
    mekanism = true
    bloodmagic = true
    create = true
    appliedenergistics2 = true
    immersiveengineering = true
    thermal = true
    pedestals = true
    silents_mechanisms = true
    boss_tools = true
    silentgear = true
    titanium = true
    immersiveposts = true
    lazierae2 = true
    nuclearcraft = true
    projectred-exploration = true
    projectred-core = true
    tconstruct = true
    chemlib = true
    createdeco = true
    createaddition = true
    steampowered = true
    biggerreactors = true
    aoa3 = true
    divinerpg = true
    morered = true
    refinedstorage = true
    forbidden_arcanus = true
    elementalcraft = true
    pamhc2foodcore = true
    alchemistry = true
    atum = true
    pneumaticcraft = true
    psi = true
    ftbjarmod = true
    miniutilities = true
    rftoolsbase = true
    aquaculture = true
