[mods]
    alchemistry = true
    aoa3 = true # advent of ascension
    appliedenergistics2 = true
    aquaculture = true
    ars_nouveau = true
    astralsorcery = true
    atum = true
    betterendforge = true
    biggerreactors = true
    bloodmagic = true
    boss_tools = true # space boss tools
    boss_tools_giselle_addon = true # space boss tools: giselle addon
    botania = true
    byg = true  # oh the biomes you'll go
    chemlib = true
    create = true
    createaddition = true
    createdeco = true
    divinerpg = true
    draconicevolution = true
    eidolon = true
    elementalcraft = true
    elgineerstools = true
    envirocore = true # environmental core
    evilcraft = true
    exnihiloae2 = true
    exnihilomekanism = true
    exnihilosequentia = true
    exnihilothermal = true
    exnihilotinkers = true
    forbidden_arcanus = true
    ftbic = true
    ftbjarmod = true
    immersiveengineering = true
    immersiveposts = true
    industrialforegoing = true
    lazierae2 = true
    mekanism = true
    miniutilities = true
    morered = true
    mysticalagriculture = true
    nuclearcraft = true
    occultism = true
    pamhc2foodcore = true # pam's harvest craft food core
    pedestals = true
    pneumaticcraft = true
    potionsmaster = true
    powah = true
    projectred-core = true
    projectred-exploration = true
    psi = true
    refinedstorage = true
    rftoolsbase = true
    silentgear = true
    silents_mechanisms = true
    steampowered = true
    tconstruct = true
    thermal = true
    titanium = true