drops = [
    # type, id, drop, count
    ['gem', 'ender_dust', 'kubejs:ender_pearl_dust', [2, 3, 4]],
    ['gem', 'amethyst', 'aoa3:amethyst', 1],
    ['metal', 'baronyte', 'kubejs:baronyte_raw', 1],
    ['metal', 'blazium', 'kubejs:blazium_raw', 1],
    ['gem', 'bloodstone', 'aoa3:bloodstone', 1],
    ['gem', 'blue_gemstone', 'aoa3:blue_gemstones', 1],
    ['gem', 'charged_runium', 'kubejs:charged_runium_raw', 1],
    ['gem', 'crystallite', 'aoa3:crystallite', 1],
    ['metal', 'elecanium', 'kubejs:elecanium_raw', 1],
    ['metal', 'emberstone', 'kubejs:emberstone_raw', 1],
    ['gem', 'gemenyte', 'aoa3:gemenyte', 1],
    ['metal', 'ghastly', 'kubejs:ghastly_raw', 1],
    ['metal', 'ghoulish', 'kubejs:ghoulish_raw', 1],
    ['gem', 'green_gemstone', 'aoa3:green_gemstones', 1],
    ['gem', 'jade', 'aoa3:jade', 1],
    ['gem', 'jewelyte', 'aoa3:jewelyte', 1],
    ['metal', 'limonite', 'kubejs:limonite_raw', 1],
    ['metal', 'lyon', 'kubejs:lyon_raw', 1],
    ['metal', 'mystite', 'kubejs:mystite_raw', 1],
    ['gem', 'ornamyte', 'aoa3:ornamyte', 1],
    ['gem', 'purple_gemstone', 'aoa3:purple_gemstones', 1],
    ['gem', 'red_gemstone', 'aoa3:red_gemstones', 1],
    ['metal', 'rosite', 'kubejs:rosite_raw', 1],
    ['gem', 'runium', 'kubejs:runium_raw', 1],
    ['metal', 'shyrestone', 'kubejs:shyrestone_raw', 1],
    ['gem', 'shyregem', 'aoa3:shyregem', 1],
    ['gem', 'skeletal', ["aoa3:skullbone_fragment", "aoa3:chestbone_fragment", "aoa3:footbone_fragment", "aoa3:legbone_fragment"], 1],
    ['metal', 'varsium', 'kubejs:varsium_raw', 1],
    ['gem', 'white_gemstone', 'aoa3:white_gemstones', 1],
    ['gem', 'yellow_gemstone', 'aoa3:yellow_gemstones', 1],
    ['gem', 'certus_quartz', 'appliedenergistics2:certus_quartz_crystal', 1],
    ['gem', 'charged_certus_quartz', 'appliedenergistics2:charged_certus_quartz_crystal', 1],
    ['gem', 'source_gem', 'ars_nouveau:mana_gem', 1],
    ['gem', 'aquamarine', 'astralsorcery:aquamarine', [1, 2, 3]],
    ['gem', 'rock_crystal', 'astralsorcery:rock_crystal', [2, 3, 4]],
    ['metal', 'starmetal', 'kubejs:starmetal_raw', 1],
    ['metal', 'nebu', 'kubejs:nebu_raw', 1],
    ['gem', 'amber', 'betterendforge:raw_amber', 1],
    ['metal', 'thallasium', 'kubejs:thallasium_raw', 1],
    ['metal', 'desh', 'kubejs:desh_raw', 1],
    ['gem', 'ice_shard', 'boss_tools:ice_shard', 3],
    ['metal', 'silicon', 'kubejs:silicon_raw', 1],
    ['gem', 'ametrine', 'byg:ametrine_gems', 1],
    ['gem', 'anthracite', 'byg:anthracite', 1],
    ['gem', 'emeraldite', 'byg:emeraldite_shards', 1],
    ['gem', 'lignite', 'byg:lignite', [4, 5, 6]],
    ['metal', 'pendorite', 'byg:raw_pendorite', 1],
    ['gem', 'apalachia', 'divinerpg:apalachia_fragments', 1],
    ['metal', 'arlemite', 'kubejs:arlemite_raw', 1],
    ['gem', 'bloodgem', 'divinerpg:bloodgem', 1],
    ['gem', 'eden', 'divinerpg:eden_fragments', 1],
    ['gem', 'mortum', 'divinerpg:mortum_fragments', 1],
    ['metal', 'realmite', 'kubejs:realmite_raw', 1],
    ['metal', 'rupee', 'kubejs:rupee_raw', 1],
    ['gem', 'skythern', 'divinerpg:skythern_fragments', 1],
    ['metal', 'torridite', 'kubejs:torridite_raw', 1],
    ['gem', 'wildwood', 'divinerpg:wildwood_fragments', 1],
    ['metal', 'draconium', 'kubejs:draconium_raw-', [2, 3, 4]],
    ['gem', 'inert_crystal', 'elementalcraft:inertcrystal', 1],
    ['gem', 'dark_gem', 'evilcraft:dark_gem', [4, 5]],
    ['gem', 'arcane_crystal', 'forbidden_arcanus:arcane_crystal', 1],
    ['gem', 'dark_rune', 'forbidden_arcanus:dark_rune', 1],
    ['gem', 'rune', 'forbidden_arcanus:rune', 1],
    ['gem', 'bitumen', 'kubejs:bitumen_gem', 1],
    ['gem', 'fluorite', 'kubejs:fluorite_gem', [2, 3, 4]],
    ['gem', 'potassium_nitrate', 'kubejs:potassium_nitrate_gem', [3, 4, 5]],
    ['gem', 'rupy', 'kubejs:ruby_gem', [2, 3, 4]],
    ['gem', 'sapphire', 'kubejs:sapphire_gem', [2, 3, 4]],
    ['gem', 'sulfur', 'kubejs:sulfur_gem', [3, 4, 5]],
    ['metal', 'aluminum', 'kubejs:aluminum_raw', 1],
    ['metal', 'bismuth', 'kubejs:bismuth_raw', 1],
    ['metal', 'cobalt', 'kubejs:cobalt_raw', 1],
    ['metal', 'iridium', 'kubejs:iridium_raw', 1],
    ['metal', 'lead', 'kubejs:lead_raw', 1],
    ['metal', 'nickel', 'kubejs:nickel_raw', 1],
    ['metal', 'osmium', 'kubejs:osmium_raw', 1],
    ['metal', 'platinum', 'kubejs:platinum_raw', 1],
    ['metal', 'silver', 'kubejs:silver_raw', 1],
    ['metal', 'tin', 'kubejs:tin_raw', 1],
    ['metal', 'titanium', 'kubejs:titanium_raw', 1],
    ['metal', 'tungsten', 'kubejs:tungsten_raw', 1],
    ['metal', 'uranium', 'kubejs:uranium_raw', 1],
    ['metal', 'zinc', 'kubejs:zinc_raw', 1],
    ['gem', 'coal', 'minecraft:coal', 1],
    ['metal', 'copper', 'kubejs:copper_raw', [2, 3, 4, 5]],
    ['gem', 'diamond', 'minecraft:diamond', 1],
    ['gem', 'emerald', 'minecraft:emerald', 1],
    ['metal', 'gold', 'kubejs:gold_raw', 1],
    ['metal', 'iron', 'kubejs:iron_raw', 1],
    ['gem', 'lapis', 'minecraft:lapis_lazuli', [4, 5, 6, 7, 8]],
    ['gem', 'quartz', 'minecraft:quartz', 1],
    ['gem', 'redstone', 'minecraft:redstone',[4, 5]],
    ['gem', 'inferium', 'mysticalagriculture:inferium_essence', [2, 3, 4]],
    ['gem', 'prosperity', 'mysticalagriculture:prosperity_shard', [1, 2, 3]],
    ['gem', 'soulium', 'mysticalagriculture:soulium_dust', [1, 2]],
    ['gem', 'dragonstone', 'botania:dragonstone', 1],
    ['metal', 'elementium', 'kubejs:elementium_raw', 1],
    ['metal', 'boron', 'kubejs:boron_raw', 1],
    ['metal', 'lithium', 'kubejs:lithium_raw', 1],
    ['metal', 'magnesium', 'kubejs:magnesium_raw', 1],
    ['metal', 'thorium', 'kubejs:thorium_raw', 1],
    ['metal', 'uraninite', 'powah:uraninite', 1],
    ['gem', 'electrotine', 'projectred-core:electrotine_dust', [4, 5]],
    ['gem', 'peridot', 'projectred-core:peridot', [2, 3, 4]],
    ['gem', 'dimensional_shard', 'rftoolsbase:dimensionalshard', 1],
    ['metal', 'azure_silver', 'silentgear:raw_azure_silver', 1],
    ['metal', 'crimson_iron', 'silentgear:raw_crimson_iron', 1],
    ['gem', 'apatite', 'thermal:apatite', [6, 7, 8]],
    ['gem', 'cinnabar', 'thermal:cinnabar', [1, 2]]
]