[ores]
# metals: raw, ore
metal_ore_drop = "raw"
metal_silktouch_affected = true

# gems: gem, ore
gem_ore_drop = "gem"
gem_silktouch_affected = true

    # metals
    [ores.metal_fortune]
    affected = true

        [ores.metal_fortune.level_1]
        possible_drops = [2]
        chance_for_each = 0.333

        [ores.metal_fortune.level_2]
        possible_drops = [2, 3]
        chance_for_each = 0.25

        [ores.metal_fortune.level_3]
        possible_drops = [2, 3, 4]
        chance_for_each = 0.2

        # extra mod
        [ores.metal_fortune.level_4]
        possible_drops = [2, 3, 4, 5]
        chance_for_each = 0.1667

    [ores.metal_multiplyer]
    overworld = 1
    nether = 1.5
    end = 2

    # gems
    [ores.gem_fortune]
    affected = true

        [ores.gem_fortune.level_1]
        possible_drops = [2]
        chance_for_each = 0.333

        [ores.gem_fortune.level_2]
        possible_drops = [2, 3]
        chance_for_each = 0.25

        [ores.gem_fortune.level_3]
        possible_drops = [2, 3, 4]
        chance_for_each = 0.2

        # extra mod
        [ores.gem_fortune.level_4]
        possible_drops = [2, 3, 4, 5]
        chance_for_each = 0.1667

    [ores.gem_multiplyer]
    overworld = 1
    nether = 1.5
    end = 2