[ores]
# metals: raw, ore
metal_ore_drop = "raw"
metal_silktouch_affected = true

# gems: gem, ore
gem_ore_drop = "gem"
gem_silktouch_affected = true

# metals
[ores.metal_fortune]
    affected = true

# gems
[ores.gem_fortune]
    affected = true

# if not existent will use value of overworld
[ores.dim_multiplyer]
    overworld = 1
    nether = 1.5
    end = 2
    mars = 1.5
    mercury = 1.5
    moon = 1.5
    venus = 1.5
    atum = 1.5