[[strata]]
    id = "stone"
    block = "minecraft:stone"
    dim = ["overworld"]
    texture = "stone"

[[strata]]
    id = "andesite"
    block = "minecraft:andesite"
    dim = ["overworld"]
    texture = "andesite"

[[strata]]
    id = "diorite"
    block = "minecraft:diorite"
    dim = ["overworld"]
    texture = "diorite"

[[strata]]
    id = "granite"
    block = "minecraft:granite"
    dim = ["overworld"]
    texture = "granite"

[[strata]]
    id = "netherrack"
    block = "minecraft:netherrack"
    dim = ["nether"]
    texture = "netherrack"

[[strata]]
    id = "end_stone"
    block = "minecraft:end_stone"
    dim = ["end"]
    texture = "end_stone"